dbname: "db_mysql"
dbtable: "music"
repo: "yanivomc"
image: "spring-music"
tag: "latest"
ubuntu@ip-172-31-13-252:~/spring-music$ cat templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname:  {{ .Values.dbname }}
  dbtable: {{ .Values.dbtable }}
  image: {{ .Values.image }}
  tag: {{ .Values.tag }}
