kind: Service      # Create new service
apiVersion: v1
metadata:
  name: animal-service
spec:
  selector:
    app: animal
  ports:          # Map incoming port to target port
  - name: http    # Setting multiple ports listterns
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
