apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
spec:
  selector:
    matchLabels:
      app: MyApp
  replicas: 2
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
