kind: Service      # Create new service
apiVersion: v1
metadata:
  name: music-service
spec:
  selector:
    app: MyApp    # Run on any pod(s) with label - app: myapp
  ports:          # Map incoming port to target port
  - name: http    # Setting multiple ports listterns
    protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
ubuntu@ip-172-31-15-128:~$ cat music-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment
spec:
  selector:
    matchLabels:
      app: MyApp
  replicas: 2
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
